# https://docs.github.com/ja/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    groups:
      actions:
        patterns:
          - "*"
    commit-message:
      prefix: "ci"

  - package-ecosystem: "swift"
    directory: "/hazkey-server"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    groups:
      swift-deps:
        patterns:
          - "*"
    commit-message:
      prefix: "deps(server)"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "monthly"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "deps(submodule)"

  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "monthly"
      timezone: "Asia/Tokyo"
    ignore:
      - dependency-name: "swift"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
    commit-message:
      prefix: "deps(devcontainer)"

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "monthly"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "deps(devcontainer)"
